// Shared ticker -> company name map (server side). Bundled into
// functions by esbuild; not deployed as its own function (leading _).
module.exports = {
RELIANCE:"Reliance Industries",TCS:"Tata Consultancy",HDFCBANK:"HDFC Bank",ICICIBANK:"ICICI Bank",
INFY:"Infosys",SBIN:"State Bank of India",BHARTIARTL:"Bharti Airtel",LICI:"Life Insurance Corp",
ITC:"ITC",LT:"Larsen & Toubro",HINDUNILVR:"Hindustan Unilever",KOTAKBANK:"Kotak Mahindra Bank",
BAJFINANCE:"Bajaj Finance",AXISBANK:"Axis Bank",MARUTI:"Maruti Suzuki",SUNPHARMA:"Sun Pharma",
HCLTECH:"HCL Technologies",NTPC:"NTPC",TATAMOTORS:"Tata Motors",ONGC:"Oil & Natural Gas",
ADANIENT:"Adani Enterprises","M&M":"Mahindra & Mahindra",WIPRO:"Wipro",ADANIPORTS:"Adani Ports",
POWERGRID:"Power Grid Corp",ULTRACEMCO:"UltraTech Cement",TITAN:"Titan Company",ASIANPAINT:"Asian Paints",
COALINDIA:"Coal India",BAJAJFINSV:"Bajaj Finserv",NESTLEIND:"Nestlé India",JSWSTEEL:"JSW Steel",
TATASTEEL:"Tata Steel",DMART:"Avenue Supermarts","BAJAJ-AUTO":"Bajaj Auto",HDFCLIFE:"HDFC Life",
SBILIFE:"SBI Life Insurance",GRASIM:"Grasim Industries",HINDALCO:"Hindalco Industries",TECHM:"Tech Mahindra",
INDUSINDBK:"IndusInd Bank",DIVISLAB:"Divi's Laboratories",DRREDDY:"Dr Reddy's Labs",CIPLA:"Cipla",
EICHERMOT:"Eicher Motors",BPCL:"Bharat Petroleum",BRITANNIA:"Britannia Industries",APOLLOHOSP:"Apollo Hospitals",
HEROMOTOCO:"Hero MotoCorp",TATACONSUM:"Tata Consumer",PIDILITIND:"Pidilite Industries",SHRIRAMFIN:"Shriram Finance",
DABUR:"Dabur India",GODREJCP:"Godrej Consumer",VEDL:"Vedanta",IOC:"Indian Oil",SIEMENS:"Siemens",
BANKBARODA:"Bank of Baroda",PNB:"Punjab National Bank",GAIL:"GAIL India",AMBUJACEM:"Ambuja Cements",
DLF:"DLF",VBL:"Varun Beverages",HAVELLS:"Havells India",ZYDUSLIFE:"Zydus Lifesciences",
TVSMOTOR:"TVS Motor",ICICIPRULI:"ICICI Prudential",ICICIGI:"ICICI Lombard",TRENT:"Trent",BEL:"Bharat Electronics",
ADANIGREEN:"Adani Green Energy",ADANIPOWER:"Adani Power",CHOLAFIN:"Cholamandalam Fin",MARICO:"Marico",
BOSCHLTD:"Bosch",SRF:"SRF",BAJAJHLDNG:"Bajaj Holdings",TORNTPHARM:"Torrent Pharma",COLPAL:"Colgate-Palmolive",
INDIGO:"InterGlobe Aviation",NAUKRI:"Info Edge",JINDALSTEL:"Jindal Steel & Power",LTIM:"LTIMindtree",
CANBK:"Canara Bank",HDFCAMC:"HDFC AMC",ABB:"ABB India",UNIONBANK:"Union Bank",IDBI:"IDBI Bank",
BERGEPAINT:"Berger Paints",PEL:"Piramal Enterprises",AUROPHARMA:"Aurobindo Pharma",LUPIN:"Lupin",
MOTHERSON:"Samvardhana Motherson",ASHOKLEY:"Ashok Leyland",MFSL:"Max Financial",PGHH:"P&G Hygiene",
UBL:"United Breweries",MUTHOOTFIN:"Muthoot Finance",PIIND:"PI Industries",SAIL:"Steel Authority",
NMDC:"NMDC",PFC:"Power Finance Corp",RECLTD:"REC",HINDPETRO:"Hindustan Petroleum",TATAPOWER:"Tata Power",
INDUSTOWER:"Indus Towers",IRCTC:"IRCTC",NHPC:"NHPC",ZOMATO:"Zomato",POLYCAB:"Polycab India",
PAYTM:"One97 (Paytm)",GMRINFRA:"GMR Airports",IGL:"Indraprastha Gas",PETRONET:"Petronet LNG",
OFSS:"Oracle Fin Services",PAGEIND:"Page Industries",ALKEM:"Alkem Laboratories",GLAND:"Gland Pharma",
BIOCON:"Biocon",IPCALAB:"Ipca Laboratories",GLENMARK:"Glenmark Pharma",LAURUSLABS:"Laurus Labs",
ABBOTINDIA:"Abbott India",SANOFI:"Sanofi India",FORTIS:"Fortis Healthcare",MAXHEALTH:"Max Healthcare",
METROPOLIS:"Metropolis Health",LALPATHLAB:"Dr Lal PathLabs",SYNGENE:"Syngene Intl",JUBLFOOD:"Jubilant FoodWorks",
DEVYANI:"Devyani International",WESTLIFE:"Westlife Foodworld",VOLTAS:"Voltas",BLUESTARCO:"Blue Star",
WHIRLPOOL:"Whirlpool India",CROMPTON:"Crompton Greaves",DIXON:"Dixon Technologies",AMBER:"Amber Enterprises",
VGUARD:"V-Guard Industries",KAJARIACER:"Kajaria Ceramics",CERA:"Cera Sanitaryware",FINPIPE:"Finolex Inds",
SUPREMEIND:"Supreme Industries",ASTRAL:"Astral",APLAPOLLO:"APL Apollo Tubes",RATNAMANI:"Ratnamani Metals",
JKCEMENT:"JK Cement",SHREECEM:"Shree Cement",RAMCOCEM:"Ramco Cements",DALBHARAT:"Dalmia Bharat",
ACC:"ACC",NUVOCO:"Nuvoco Vistas",BIRLACORPN:"Birla Corporation",STARCEMENT:"Star Cement",
HEIDELBERG:"HeidelbergCement",JSWENERGY:"JSW Energy",TORNTPOWER:"Torrent Power",CESC:"CESC",
SJVN:"SJVN",IEX:"Indian Energy Exch",PTC:"PTC India",KEC:"KEC International",KALPATPOWR:"Kalpataru Projects",
THERMAX:"Thermax",CUMMINSIND:"Cummins India",AIAENG:"AIA Engineering",GRINDWELL:"Grindwell Norton",
SKFINDIA:"SKF India",SCHAEFFLER:"Schaeffler India",TIMKEN:"Timken India",BHARATFORG:"Bharat Forge",
SUNDRMFAST:"Sundram Fasteners",ENDURANCE:"Endurance Tech",BALKRISIND:"Balkrishna Inds",APOLLOTYRE:"Apollo Tyres",
MRF:"MRF",CEATLTD:"CEAT",JKTYRE:"JK Tyre",EXIDEIND:"Exide Industries",AMARAJABAT:"Amara Raja Energy",
HAL:"Hindustan Aeronautics",BDL:"Bharat Dynamics",MAZDOCK:"Mazagon Dock",COCHINSHIP:"Cochin Shipyard",
GRSE:"Garden Reach Ship",IRFC:"Indian Railway Fin",RVNL:"Rail Vikas Nigam",RAILTEL:"RailTel",
IRCON:"Ircon Intl",NBCC:"NBCC India",NCC:"NCC",PNCINFRA:"PNC Infratech",KNRCON:"KNR Constructions",
CONCOR:"Container Corp",BLUEDART:"Blue Dart Express",TCIEXP:"TCI Express",DELHIVERY:"Delhivery",
MAHLOG:"Mahindra Logistics",GUJGASLTD:"Gujarat Gas",MGL:"Mahanagar Gas",AEGISCHEM:"Aegis Logistics",
CASTROLIND:"Castrol India",GULFOILLUB:"Gulf Oil Lubricants",DEEPAKNTR:"Deepak Nitrite",AARTIIND:"Aarti Industries",
NAVINFLUOR:"Navin Fluorine",FLUOROCHEM:"Gujarat Fluorochem",VINATIORGA:"Vinati Organics",ATUL:"Atul",
CLEAN:"Clean Science",ALKYLAMINE:"Alkyl Amines",BALAMINES:"Balaji Amines",TATACHEM:"Tata Chemicals",
GNFC:"GNFC",CHAMBLFERT:"Chambal Fertilisers",COROMANDEL:"Coromandel Intl",UPL:"UPL",RALLIS:"Rallis India",
SUMICHEM:"Sumitomo Chemical",BAYERCROP:"Bayer CropScience",SUDARSCHEM:"Sudarshan Chemical",
JUBLINGREA:"Jubilant Ingrevia",FINEORG:"Fine Organic",GALAXYSURF:"Galaxy Surfactants",EIDPARRY:"EID Parry",
BALRAMCHIN:"Balrampur Chini",TRIVENI:"Triveni Engineering",DCMSHRIRAM:"DCM Shriram",KANSAINER:"Kansai Nerolac",
AKZOINDIA:"Akzo Nobel India",INDIGOPNTS:"Indigo Paints",SHEELAFOAM:"Sheela Foam",CENTURYPLY:"Century Plyboards",
GREENPLY:"Greenply Industries",GREENPANEL:"Greenpanel Inds",JYOTHYLAB:"Jyothy Labs",EMAMILTD:"Emami",
GILLETTE:"Gillette India",HONAUT:"Honeywell Automation","3MINDIA":"3M India",RAYMOND:"Raymond",
ARVIND:"Arvind",KPRMILL:"KPR Mill",TRIDENT:"Trident",WELSPUNLIV:"Welspun Living",WELCORP:"Welspun Corp",
RHIM:"RHI Magnesita",JINDALSAW:"Jindal Saw",APARINDS:"Apar Industries",FINOLEXIND:"Finolex Industries",
POLYPLEX:"Polyplex Corp",UFLEX:"UFlex",EPL:"EPL",TIMETECHNO:"Time Technoplast",VIPIND:"VIP Industries",
SAFARI:"Safari Industries",RELAXO:"Relaxo Footwears",BATAINDIA:"Bata India",METROBRAND:"Metro Brands",
CAMPUS:"Campus Activewear",KALYANKJIL:"Kalyan Jewellers",TITAGARH:"Titagarh Rail",JWL:"Jupiter Wagons",
STARHEALTH:"Star Health",NIACL:"New India Assurance",GICRE:"GIC Re",POLICYBZR:"PB Fintech",
CDSL:"CDSL",CAMS:"CAMS",BSE:"BSE",MCX:"Multi Commodity Exch",ANGELONE:"Angel One",IIFL:"IIFL Finance",
"360ONE":"360 ONE WAM","NAM-INDIA":"Nippon Life AMC",UTIAMC:"UTI AMC",ABCAPITAL:"Aditya Birla Capital",
"L&TFH":"L&T Finance",SUNDARMFIN:"Sundaram Finance","M&MFIN":"M&M Financial",MANAPPURAM:"Manappuram Finance",
CREDITACC:"CreditAccess Gram",FIVESTAR:"Five-Star Business",AAVAS:"Aavas Financiers",APTUS:"Aptus Value Hsg",
HOMEFIRST:"Home First Finance",CANFINHOME:"Can Fin Homes",PNBHOUSING:"PNB Housing",LICHSGFIN:"LIC Housing Fin",
REPCO:"Repco Home Fin",JMFINANCIL:"JM Financial",MOTILALOFS:"Motilal Oswal",ANANDRATHI:"Anand Rathi",
PRUDENT:"Prudent Corp",FEDERALBNK:"Federal Bank",BANDHANBNK:"Bandhan Bank",IDFCFIRSTB:"IDFC First Bank",
RBLBANK:"RBL Bank",AUBANK:"AU Small Fin Bank",CITYUNIONBANK:"City Union Bank",KARURVYSYA:"Karur Vysya Bank",
SOUTHBANK:"South Indian Bank","J&KBANK":"J&K Bank",DCBBANK:"DCB Bank",INDIANB:"Indian Bank",
IOB:"Indian Overseas Bank",CENTRALBK:"Central Bank",MAHABANK:"Bank of Maharashtra",UCOBANK:"UCO Bank",
PSB:"Punjab & Sind Bank",EQUITASBNK:"Equitas Small Fin",UJJIVANSFB:"Ujjivan Small Fin",SURYODAY:"Suryoday SFB",
TATAELXSI:"Tata Elxsi",COFORGE:"Coforge",PERSISTENT:"Persistent Systems",LTTS:"L&T Technology",
MPHASIS:"Mphasis",KPITTECH:"KPIT Technologies",CYIENT:"Cyient",SONACOMS:"Sona BLW Precision",
ZENSARTECH:"Zensar Tech",BIRLASOFT:"Birlasoft",INTELLECT:"Intellect Design",NEWGEN:"Newgen Software",
MASTEK:"Mastek",HAPPSTMNDS:"Happiest Minds",LATENTVIEW:"LatentView",TANLA:"Tanla Platforms",
ROUTE:"Route Mobile",FSL:"Firstsource",RATEGAIN:"RateGain Travel",MAPMYINDIA:"C.E. Info (MapmyIndia)",
SBICARD:"SBI Cards",POONAWALLA:"Poonawalla Fincorp",ABFRL:"Aditya Birla Fashion",VMART:"V-Mart Retail",
SHOPERSTOP:"Shoppers Stop",GOCOLORS:"Go Fashion",VEDANT:"Vedant Fashions",PVRINOX:"PVR INOX",
SUNTV:"Sun TV Network",ZEEL:"Zee Entertainment",NETWORK18:"Network18 Media",TV18BRDCST:"TV18 Broadcast",
SAREGAMA:"Saregama India",NAZARA:"Nazara Technologies",DBCORP:"D.B. Corp",JAGRAN:"Jagran Prakashan",
HATHWAY:"Hathway Cable",DISHTV:"Dish TV",GTPL:"GTPL Hathway",TIPSINDLTD:"Tips Music",ENIL:"Entertainment Network",
OBEROIRLTY:"Oberoi Realty",GODREJPROP:"Godrej Properties",LODHA:"Macrotech (Lodha)",PRESTIGE:"Prestige Estates",
BRIGADE:"Brigade Enterprises",SOBHA:"Sobha",PHOENIXLTD:"Phoenix Mills",MAHLIFE:"Mahindra Lifespace",
SUNTECK:"Sunteck Realty",KOLTEPATIL:"Kolte-Patil",ANANTRAJ:"Anant Raj",IBREALEST:"Indiabulls Real Est",
SIGNATURE:"Signatureglobal",PURVA:"Puravankara",ASHIANA:"Ashiana Housing",GESHIP:"Great Eastern Ship",
SCI:"Shipping Corp",RITES:"RITES",ENGINERSIN:"Engineers India",HUDCO:"HUDCO",SOLARINDS:"Solar Industries",
GHCL:"GHCL",TATACOMM:"Tata Communications","3IINFOTECH":"3i Infotech",KFINTECH:"KFin Technologies",
INDIAMART:"IndiaMART",JUSTDIAL:"Just Dial",AFFLE:"Affle India",EASEMYTRIP:"Easy Trip Planners",
IXIGO:"Le Travenues (ixigo)",TBOTEK:"TBO Tek",DREAMFOLKS:"Dreamfolks Services",GODREJIND:"Godrej Industries",
GODREJAGRO:"Godrej Agrovet",AVANTIFEED:"Avanti Feeds",CCL:"CCL Products",HERITGFOOD:"Heritage Foods",
DODLA:"Dodla Dairy",HATSUN:"Hatsun Agro",KRBL:"KRBL",LTFOODS:"LT Foods",USHAMART:"Usha Martin",
SHYAMMETL:"Shyam Metalics",GPIL:"Godawari Power",SARDAEN:"Sarda Energy",MAITHANALL:"Maithan Alloys",
KIRLOSENG:"Kirloskar Oil",KIRLOSBROS:"Kirloskar Brothers",ELGIEQUIP:"Elgi Equipments",TIINDIA:"Tube Investments",
GREAVESCOT:"Greaves Cotton",VSTTILLERS:"VST Tillers",ESCORTS:"Escorts Kubota",FORCEMOT:"Force Motors",
WABAG:"VA Tech Wabag",EMUDHRA:"eMudhra",DATAPATTNS:"Data Patterns",ZENTEC:"Zen Technologies",
PARAS:"Paras Defence",ASTRAMICRO:"Astra Microwave",MTARTECH:"MTAR Technologies",IDEAFORGE:"ideaForge",
JTLIND:"JTL Industries",SANSERA:"Sansera Engineering",UNOMINDA:"Uno Minda",DALMIASUG:"Dalmia Bharat Sugar"
};
