[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Friendly paths -> functions
[[redirects]]
  from = "/api/yahoo"
  to = "/.netlify/functions/yahoo"
  status = 200

[[redirects]]
  from = "/api/movers"
  to = "/.netlify/functions/movers"
  status = 200
