// One-shot: fill the desc field for every NOTEBOOKS company that was
// ticker-only after the bulk-add. Business profile only — no broker
// views, no financial figures. Sourced from public company filings,
// websites and annual reports.

const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, '..', 'data', 'companies.json');
const companies = JSON.parse(fs.readFileSync(file, 'utf8'));

const DESCS = {
  'AIA Engineering': "Among the world's leading manufacturers of high-chrome mill internals — grinding media and mill liners — used in cement, mining and thermal-power grinding circuits. Ahmedabad-based; exports drive the bulk of revenue with replacement-cycle wear consumables as the recurring annuity.",
  'ASK Automotive': "Auto-components supplier specialising in advanced two-wheeler braking (drum brakes, disc-brake calipers), aluminium light-weighting precision parts and wheel-assembly components. Customer base spans Hero MotoCorp, Bajaj Auto, TVS, Honda Motorcycle and Royal Enfield.",
  'Adani Enterprises': "Flagship and incubator of the Adani Group. Houses the integrated resources business (coal trading, mining services, mine developer) and the group's emerging ventures — airports, road infrastructure, data centres, solar manufacturing, green hydrogen, copper, defence and FMCG (Adani Wilmar's residual). Successful businesses are typically demerged into separately listed group companies.",
  'Adani Ports and SEZ': "India's largest private-sector port operator. Operates a network of 14+ ports along the Indian coastline — anchored by Mundra — handling containers, dry bulk, liquid bulk and crude. Also runs a port-led logistics platform spanning warehousing, rail-haulage and inland container depots.",
  'Aditya Birla Fashion and Retail': "Aditya Birla Group's apparel and lifestyle retail platform. Brand portfolio spans Madura Fashion menswear (Louis Philippe, Van Heusen, Allen Solly, Peter England), value/large-format Pantaloons, the TCNS-acquired women's-wear stable (W, Aurelia, Wishful) and licensed brands (Reebok, Hackett, American Eagle). Distributed through exclusive-brand stores, large-format Pantaloons outlets and multi-brand departmental stores.",
  'Aegis Logistics': "Liquid-logistics specialist. Owns and operates LPG and petrochemical storage terminals at key Indian ports along with an LPG sourcing and distribution business; expanding into ammonia handling and other green-fuel intermediates.",
  'Alkem Laboratories': "Top-five domestic-formulation pharma company anchored by anti-infectives. Big-brand franchises include Clavam, Taxim-O and Pan in anti-infectives and gastro, plus chronic-therapy build-out across cardiology, diabetology and neuropsychiatry. Also has a US generics business led by oral solids.",
  'Amara Raja Energy and Mobility': "India's #2 lead-acid battery maker, selling under the Amaron and PowerZone brands across automotive, industrial (UPS, telecom) and home-inverter segments. Building out a new-energy vertical anchored by a lithium-ion cell and pack manufacturing platform plus EV-charging infrastructure.",
  'Apar Industries': "Diversified electrical-engineering company. India's largest conductor manufacturer (overhead transmission), the largest domestic producer of specialty oils (transformer oils, industrial lubricants) and a growing power & telecom cables business; global supplier to T&D utilities and OEMs.",
  'Apollo Hospitals': "India's largest private hospital chain. Operates 70+ hospitals with strong tertiary-care programmes in cardiology, oncology, organ transplants and neurosciences; complementary businesses include Apollo Pharmacies (retail), Apollo HealthCo (digital health, diagnostics and online pharmacy) and Apollo 24|7 telehealth.",
  'Ashok Leyland': "Hinduja Group's commercial-vehicle flagship. India's #2 medium- and heavy-commercial-vehicle manufacturer with a growing light-CV and bus portfolio; defence mobility platforms (Stallion family) and the Switch Mobility electric-bus/LCV subsidiary build out the next-generation product slate.",
  'Asian Paints': "India's largest paint company by a wide margin. Decorative-paints leader through Royale, Apex, Apcolite and Tractor; growing exposure in industrial paints, automotive coatings and waterproofing; recently expanded into home décor adjacencies (kitchen, bath, lighting). Anchored by a dense dealer network and category-defining brand equity.",
  'Ather Energy': "Bengaluru-based electric two-wheeler manufacturer. Designs and builds connected electric scooters — the Ather 450 family and family-oriented Ather Rizta — and runs the Ather Grid fast-charging network. Hero MotoCorp is the anchor strategic shareholder alongside the founders.",
  'Aurobindo Pharma': "Vertically-integrated generics pharma spanning APIs, formulations and biosimilars. Large US generics franchise (oral solids and injectables) plus growing Europe and emerging-market exposure; expanding into biosimilars and vaccines through subsidiary CuraTeQ Biologics.",
  'Bajaj Finance': "India's largest non-bank lender. Diversified retail and SME loan book spanning consumer durables, two-wheeler, lifestyle, EMI cards, personal loans and SME lending, complemented by home loans via Bajaj Housing Finance. Anchor lending business of the Bajaj Finserv platform with a large captive customer franchise.",
  'Belrise Industries': "Auto-components supplier to two-wheeler and four-wheeler OEMs. Manufactures chassis and metal components, polymer assemblies, suspension parts and seating systems; recently listed.",
  'Blue Jet Healthcare': "Pharma intermediates and contrast-media manufacturer. Among the global suppliers of iodinated contrast media (for diagnostic imaging) and high-intensity sweeteners (saccharin), with a growing pharma-intermediates franchise serving innovator clients.",
  'BrainBees Solutions': "Operator of FirstCry, India's largest kidswear and baby-care omnichannel retailer. Online plus 1,000+ stores, own brands (BabyHug) and partner brands; also owns the BabyChakra D2C platform and runs the GlobalBees house-of-brands roll-up.",
  'Britannia Industries': "Wadia Group's branded foods company. India's biggest biscuit maker — Good Day, NutriChoice, Milk Bikis, Marie Gold, Tiger, Treat, Bourbon — with growing adjacencies across dairy, breads, cakes, rusks, salty snacks and croissants.",
  'CEAT': "RPG Group tyre manufacturer. Makes truck-bus, passenger-car, two-wheeler, off-road and farm tyres for the Indian market plus exports; replacement-led brand strategy alongside a growing OEM-fitment business.",
  'Campus Activewear': "Branded sports and athleisure footwear specialist. Sells across multi-brand outlets, exclusive-brand stores and e-commerce with a value-for-money sneaker focus; aggressive D2C and own-store rollout.",
  'Cartrade Tech': "Auto classifieds and remarketing platform. Operates CarTrade, CarWale and BikeWale on the consumer-facing side; Adroit Inspection (used-vehicle inspection services) and Shriram Automall (B2B used-vehicle auctions and physical yards) on the B2B side.",
  'Cello World': "Branded consumer-housewares company. Plastic and steel kitchenware, glassware (Cello Opalware), insulated water bottles, lunch boxes and writing instruments (Cello pens); pan-India distribution plus a growing premium portfolio.",
  'Colgate-Palmolive (India)': "Indian subsidiary of Colgate-Palmolive (US). Market leader in oral care — toothpastes (Colgate Strong Teeth, Total, MaxFresh, Visible White, Vedshakti) and toothbrushes — and a smaller personal-care portfolio under the Palmolive masterbrand.",
  'Concord Biotech': "Fermentation-based API specialist. Among the global leaders in immunosuppressant APIs (tacrolimus, cyclosporine, mycophenolate, sirolimus) plus oncology fermentation products; expanding into formulations and partnered finished dosage forms.",
  'Container Corporation of India': "Government-owned (Ministry of Railways) container train operator. India's largest rail-based container logistics platform with own container terminals, inland container depots and rolling stock; also offers cross-border movement to Bangladesh and Nepal.",
  'Cummins India': "Indian subsidiary of Cummins Inc. Manufactures diesel and natural-gas engines, gensets and power-generation systems for industrial, automotive and stationary applications; also distributes filtration, after-treatment and exhaust products.",
  'Cyient': "IT services and engineering R&D company. Provides digital engineering and product-development services to aerospace, transportation, medical-devices, semiconductor, energy and utilities clients; the semiconductor and electronics manufacturing IDM business has been spun off into separately listed Cyient DLM.",
  'Dabur India': "Diversified consumer-goods company anchored in Ayurveda. Big brands span hair care (Vatika, Dabur Amla, Brahmi Amla), oral care (Dabur Red, Meswak), foods and beverages (Real fruit juices, Hommade), home care (Odonil, Odomos) and OTC healthcare (Chyawanprash, Honitus, Lal Tail, Pudin Hara). Among the deepest rural distribution networks in Indian FMCG.",
  'Dalmia Bharat': "India's fourth-largest cement producer. Capacity concentrated in East, South and North-East India, sold under the Dalmia Cement and Konark brands; high blended-cement share and an early-mover focus on the net-zero transition.",
  'Dish TV': "Direct-to-Home (DTH) TV broadcaster. Operates the Dish TV and D2H brands; structurally challenged as Indian households shift to OTT and broadband-delivered video.",
  "Divi's Laboratories": "Hyderabad-based API and custom-synthesis specialist. Among the world's top producers of generic APIs and a major partner for global innovators on patented intermediates; building out nutraceutical ingredients and contrast-media intermediates.",
  'EPL': "World's largest manufacturer of laminated and extruded plastic tubes (the former Essel Propack). Supplies tube packaging to global FMCG customers across oral care, beauty/cosmetics, pharma, food and home care, with plants spread across India, the Americas, Europe and Asia.",
  'Eicher Motors': "Owner of Royal Enfield — the market-leading mid-size motorcycle brand — and a 50/50 JV partner in Volvo Eicher Commercial Vehicles (trucks and buses). Strong brand-led pricing power in the global middleweight motorcycle segment.",
  'Emami': "Branded personal-care and ayurvedic-OTC company. Anchor brands include Boroplus antiseptic cream, Navratna cooling oil, Smart & Handsome men's grooming, Zandu (ayurvedic OTC) and Kesh King (hair oils and shampoos). Positioned in the masstige segment.",
  'Entero Healthcare': "Pan-India pharma-distribution platform. Aggregates regional pharma distributors into a single supply-chain network serving pharmacies and hospitals; classic consolidator play in a highly fragmented industry.",
  'Eureka Forbes': "Home and lifestyle solutions company. Owns Aquaguard (water purifiers — category creator), Forbes vacuum cleaners and Euroclean home-cleaning products; controlled by Advent International since 2022.",
  'FSN E-commerce Ventures': "Operator of Nykaa — India's leading beauty and personal-care omnichannel retailer. Sells through Nykaa.com, Nykaa Fashion and 200+ physical stores, supported by own brands (Nykaa Cosmetics, Nykaa Naturals, KAY Beauty, Twenty Dresses) alongside the marquee global brand catalogue.",
  'Finolex Cables': "India's #2 electrical cables and wires brand. Power, communication and infrastructure cables anchor revenue, complemented by a growing electrical-consumer-goods portfolio (switches, fans, lighting, water heaters) under the Finolex name.",
  'Finolex Industries': "India's #2 PVC pipes brand for agriculture and plumbing — the only major Indian pipe maker that is backward-integrated into PVC resin. Distribution reaches deep into rural irrigation belts alongside the urban plumbing channel.",
  'Fortis Healthcare': "IHH-Healthcare-controlled Indian hospital chain. Operates ~28 hospitals across India and Sri Lanka with strong cardiac sciences, orthopaedics, neurology and oncology programmes; SRL Diagnostics is a major contributor to the integrated diagnostics business.",
  'GAIL India': "India's largest natural-gas transmission and marketing company (government-owned). Operates the country's largest gas-pipeline network plus petrochemicals (Pata), LPG production and city-gas distribution joint ventures; central to India's gas-economy build-out.",
  'GMR Airports': "Airport operator. Runs Delhi (DIAL), Hyderabad (GHIAL) and Goa Mopa airports plus international assets (Cebu in the Philippines, Crete in Greece, Medan in Indonesia in development); also developing airport-led commercial real estate and aero-mall infrastructure.",
  'General Insurance Corp of India': "Government-owned reinsurer. India's #1 reinsurance company providing capacity to domestic non-life insurers across fire, motor, marine, agriculture, engineering and life-treaty business, with growing inward international writings.",
  'Godrej Consumer Products': "Godrej Group's branded FMCG flagship. Strong franchises in home insecticides (Good Knight, HIT), hair colour (Godrej Expert), air-care (AER), liquid detergent (Ezee) and personal wash (Cinthol, Godrej No. 1). Sizeable international exposure to Indonesia and Africa.",
  'Grasim Industries': "Aditya Birla Group's diversified manufacturing holding. Anchored by viscose-staple-fibre (one of the world's largest producers) and chemicals (caustic soda, chlor-alkali); also the holding entity for UltraTech Cement (listed separately) and the new Birla Opus decorative-paints venture.",
  'Gujarat Gas': "Gujarat-government-owned city-gas-distribution company. India's largest CGD operator by volume — Surat, Vadodara, Ahmedabad Rural and 40+ other geographical areas — selling PNG (industrial, commercial, domestic) and CNG.",
  'Gujarat Pipavav Port': "APM-Terminals-operated multi-cargo port on Gujarat's west coast. Handles containers, dry bulk, liquid bulk and roll-on/roll-off cargo; strong dedicated-rail connectivity to North and Central India hinterlands.",
  'Hitachi Energy India': "Indian subsidiary of Hitachi Energy (Switzerland). Power-grid equipment and solutions — transformers, HVDC, gas-insulated switchgear, FACTS systems and grid-automation — supplied to PGCIL, state utilities and private grid developers.",
  'Honasa Consumer': "Direct-to-consumer beauty and personal-care company. Anchor brand Mamaearth (toxin-free baby and personal care); house of brands extends into The Derma Co., Aqualogica, BBLUNT (haircare), Dr Sheth's and Ayuga.",
  'Hyundai Motor India': "Indian subsidiary of Hyundai Motor Company (Korea). India's #2 passenger-vehicle manufacturer, with strong franchises in SUVs (Creta, Venue, Alcazar, Tucson) and hatchbacks (i20, Exter, Grand i10 Nios); first major automotive OEM IPO in India since Maruti.",
  'ICRA': "Credit-ratings and research company. Moody's-affiliated; rates corporate debt, structured-finance instruments, banks, insurers and SMEs in India. ICRA Analytics provides knowledge-services, risk and outsourcing solutions.",
  'IPCA Laboratories': "Formulations and API pharma company. Strong franchise in anti-malarials (artemether-lumefantrine combinations), pain management (NSAIDs) and cardiovascular generics; revenue mix spans India, emerging markets, the UK (Unichem-acquired plants) and tender business.",
  'IRB Infrastructure': "Toll-roads and highways operator. Builds, operates and tolls BOT highways across India through IRB and the listed IRB InvIT (private InvIT for cash-flow recycling); among India's largest private highway operators by toll collection.",
  'ITC': "Diversified conglomerate. Cigarettes — market leader through Gold Flake, Classic, Wills, Navy Cut — drives the bulk of profit, while a growing FMCG portfolio (Aashirvaad atta, Sunfeast biscuits, Bingo snacks, Yippee noodles, Vivel and Mangaldeep) plus hotels (ITC and Welcomhotel — being demerged), paperboards and agribusiness verticals diversify the franchise.",
  'IndiGo': "Operated by InterGlobe Aviation. India's #1 airline with ~60% domestic market share; low-cost carrier with a point-to-point Airbus A320/A321 backbone and ATR turboprops for regional routes; rapidly expanding internationally across the Middle East, ASEAN, Central Asia and Europe.",
  'Indigo Paints': "India's #5 decorative-paints brand. Differentiated portfolio anchored by category-creator products (Metallic Emulsions, Tile-Coat Emulsion, Bright Ceiling Coat) alongside the regular emulsion and enamel range; growing dealer network in Tier-3/4 towns.",
  'Indus Towers': "India's largest passive-infrastructure tower company. Owns and leases ~225,000 telecom towers to Indian wireless operators (Bharti Airtel, Vodafone Idea, Reliance Jio); created from the Indus + Bharti Infratel merger.",
  'Info Edge': "Internet platforms holding company. Owns Naukri.com (#1 jobs portal), 99acres (real estate), Jeevansathi (matrimony), Shiksha (higher-education) and a portfolio of internet investments — including a major stake in Zomato (separately listed).",
  'InterGlobe Aviation': "Operator of IndiGo, India's largest airline. Low-cost-carrier model with a point-to-point Airbus A320/A321 fleet plus ATR turboprops; ~60% domestic market share and a rapidly expanding international network.",
  'International Gemmological Institute': "Global diamond, gemstone and jewellery certification lab. Operates ~30 labs across 10+ countries; long-standing certification standards for natural and lab-grown diamonds, coloured stones and finished jewellery; among the world's top three gem labs.",
  'JK Cement': "Singhania-promoted cement maker. Strong in grey cement across Northern and Central India and India's leader in white cement and wall putty (JK Wall Putty); growing presence in tile adhesives, waterproofing and paints.",
  'JSW Cement': "JSW Group's cement business. Operates the world's largest GGBS-based (slag-from-JSW-Steel) green-cement platform alongside clinker plants in South and East India; emphasis on low-carbon cement and a net-zero pathway.",
  'JSW Steel': "JSW Group's flagship integrated steel maker. India's #2 steel producer with capacity at Vijayanagar, Dolvi and Salem domestically and overseas assets in the US and Italy; growing value-added mix in automotive grades and downstream coated lines.",
  'Jubilant FoodWorks': "India's largest master-franchisee of Domino's Pizza (1,900+ outlets) and Dunkin' Donuts; also operates Popeyes chicken QSR and the in-house Hong's Kitchen Chinese QSR brand. Pivoting toward an integrated digital-first food-tech platform.",
  'Jubilant Ingrevia': "Specialty-chemicals and life-science ingredients company. Pyridine and pyridine-derivatives leader plus life-science chemicals, nutrition ingredients and health solutions; serves pharma, agrochemicals and food customers globally.",
  'Jupiter Wagons': "Railway-wagon and rolling-stock manufacturer. Makes freight wagons for Indian Railways, brake systems and rail components; also runs a small commercial-vehicle business (Jupiter Tatra Trucks) and is building EV-mobility products.",
  'Kotak Mahindra Bank': "Uday Kotak-founded private-sector bank. Universal-banking franchise spanning retail and corporate lending, deposits and treasury, supported by a strong asset-management arm (Kotak Mahindra AMC), Kotak Life Insurance, Kotak General Insurance, Kotak Securities and Kotak Investment Banking.",
  'L&T': "India's largest infrastructure-EPC conglomerate. Executes heavy civil infrastructure (transport, water, hydrocarbon, power), defence platforms and heavy engineering; also operates IT services (via LTIMindtree and LTTS), financial services (L&T Finance) and minerals/manufacturing arms.",
  'L&T Finance': "L&T Group's diversified NBFC. Lending focused on rural (farm equipment, two-wheeler, micro-finance), urban (consumer loans, home loans, SME) and SME finance; pivoting to a fully retailised lending franchise.",
  'LIC India': "India's largest life insurer (government-owned majority). Pan-India distribution anchored by an agency force of 1.3 million+; participating, non-participating, ULIP and group business across individual and group life. Holds one of the largest equity portfolios in listed Indian companies.",
  'LTIMindtree': "L&T-Infotech + Mindtree merged IT-services major (L&T Group). Digital transformation, cloud, data and AI services with deep verticals in BFSI, technology-media-telecom, manufacturing and retail.",
  'Larsen & Toubro': "India's largest infrastructure-EPC conglomerate. Builds heavy civil infrastructure (transport, water, hydrocarbon, power), defence platforms and heavy engineering; also runs IT services (LTIMindtree, LTTS), financial services (L&T Finance) and minerals/manufacturing arms.",
  'Lemon Tree Hotels': "Mid-market hotel chain. Operates Lemon Tree (upper-mid), Red Fox (mid), Lemon Tree Premier and Aurika (upscale) brands across 90+ properties in India; owned, leased, managed and franchised inventory mix.",
  'Lloyds Metals and Energy': "Iron-ore mining and sponge-iron producer. Operates the Surjagarh iron-ore mine in Maharashtra with growing capacity; expanding both backward (mining) and forward (long-products steel via under-construction integrated facilities) into the value chain.",
  'Marico': "Branded FMCG company. Anchored by Parachute coconut oil (market leader) and Saffola (refined edible oils, breakfast and masala oats), with a growing personal-care portfolio (Beardo, Just Herbs, Plix, Pure Sense) and a sizeable international business (Bangladesh, Vietnam, MENA).",
  'Max Healthcare': "Private hospital chain. Operates 22+ hospitals across North India (Saket, Patparganj, Vaishali, Mohali, Dehradun) and a growing presence in Mumbai; tertiary-care programmes in oncology, cardiac sciences, orthopaedics and minimal-access surgery.",
  'Metro Brands': "Branded footwear retailer. Operates Metro Shoes, Mochi, Walkway, Crocs (master franchise), Da Vinchi, Fila and FitFlop stores across India; multi-brand-outlet (MBO) format anchored in premium and aspirational segments.",
  'Mphasis': "Blackstone-controlled IT-services major. Specialises in BFSI (banking, capital markets, insurance) with a growing cloud, customer-experience and applied-AI services offering; close partnership with hyperscalers.",
  'NMDC': "India's largest iron-ore miner (government-owned). Operates large-scale mines at Bailadila (Chhattisgarh) and Donimalai (Karnataka), supplying domestic steel majors; an under-construction integrated steel plant at Nagarnar is being demerged.",
  'NTPC': "India's largest power-generation company (government-owned). Coal-fired thermal generation forms the backbone, with a growing renewables platform housed in separately listed NTPC Green Energy alongside gas, hydro and nuclear capacity. Major beneficiary of India's power-demand cycle and the energy transition.",
  'Narayana Hrudayalaya': "Bengaluru-headquartered hospital chain. Originally a cardiac-care specialist, today operates 22+ multispecialty hospitals across India and the Cayman Islands; known for high-volume, low-cost tertiary care across cardiology, oncology and neurosciences.",
  'Navin Fluorine': "Fluorine-chemistry specialist. Operates inorganic fluorides, refrigerant gases and specialty fluorochemicals businesses, with a fast-growing high-value contract development and manufacturing (CDMO) franchise serving global pharma and agrochemical innovators.",
  'ONGC': "Government-owned upstream oil and gas major. India's largest crude-oil and natural-gas producer with assets in western offshore (Mumbai High), eastern offshore (KG-DWN) and a wide onshore footprint; ONGC Videsh handles the international E&P portfolio.",
  'Oil India': "Government-owned upstream oil and gas company. Produces crude oil and natural gas, primarily from Assam and Rajasthan; also runs an LPG plant and holds a controlling stake in the Numaligarh refinery (NRL).",
  'Oil and Natural Gas': "Government-owned ONGC — India's largest upstream oil and gas producer. Operates crude-oil and natural-gas blocks across western offshore (Mumbai High), eastern offshore (KG-DWN) and onshore; ONGC Videsh runs the international E&P portfolio.",
  'Ola Electric': "Ola Group EV two-wheeler manufacturer. Designs and builds the Ola S1 family of electric scooters at its Futurefactory in Tamil Nadu; building battery-cell manufacturing under the Bharat Cell programme and developing an electric motorcycle platform.",
  'One 97 Communications': "Operator of Paytm — India's home-grown payments and financial-services platform. Consumer payments (UPI, wallet, bills), merchant payments (QR, Soundbox, EDC), distribution of credit (loan-marketplace model) and wealth-tech; restructured following the Paytm Payments Bank wind-down.",
  'PI Industries': "Agrochemical custom-synthesis-manufacturing (CSM) specialist. Contract-manufactures patented agrochemical molecules for global innovators (Syngenta, Bayer, BASF and others), alongside an in-licensed domestic agrochemical-products portfolio; expanding into pharma CSM through subsidiary acquisitions.",
  'Page Industries': "Exclusive licensee of Jockey (innerwear) and Speedo (swimwear) in India, Sri Lanka, Bangladesh, Nepal and the UAE. Dominant share in branded men's innerwear, with a growing women's and athleisure portfolio.",
  'Patanjali Foods': "Ramdev-backed FMCG and edible-oils company (formerly Ruchi Soya). Operates Patanjali-branded foods, edible oils (Nutrela, Mahakosh, Ruchi Gold), nutraceuticals and a small home & personal-care business; the largest player in Indian soya nutrition through Nutrela.",
  'Praj Industries': "Bioenergy and process-engineering company. Designs and builds ethanol plants (first-generation, second-generation and biofuels), water/wastewater treatment systems and process equipment for breweries, pharma and chemicals; among India's leading ethanol-plant integrators.",
  'Prestige Estates Projects': "Bengaluru-headquartered real-estate developer. Operates residential, office, retail-mall (Forum) and hospitality (Conrad, JW Marriott) developments across South India, Mumbai and NCR; one of India's top residential developers by booking value.",
  "Rainbow Children's Hospitals": "Hyderabad-headquartered paediatric and women's hospital chain. Operates 17+ multispecialty paediatric and perinatal hospitals primarily in South India; tertiary-care focus on neonatal intensive care, paediatric oncology and foetal medicine.",
  "Rainbow Children's Medicare": "Hyderabad-headquartered paediatric and women's hospital chain. Operates 17+ multispecialty paediatric and perinatal hospitals primarily in South India; tertiary-care focus on neonatal intensive care, paediatric oncology and foetal medicine.",
  'RateGain': "Travel-tech SaaS company. Provides distribution, revenue management, rate intelligence and pricing analytics solutions to hotels, airlines, car-rental companies and OTAs globally; subscription-led SaaS revenue model.",
  'Reliance Industries': "Mukesh Ambani-led conglomerate. Oil-to-chemicals (the world's largest single-site refinery at Jamnagar plus petrochemicals), digital services (Jio — India's #1 telecom plus JioFiber and JioAirFiber), retail (Reliance Retail — India's largest retailer across grocery, fashion, electronics, jewellery and pharmacy) and a new-energy platform (giga-factories for solar, batteries, electrolysers and fuel cells). Also runs media (Network18, the JioStar JV) and an upstream oil & gas business.",
  'SAMHI Hotels': "Branded mid-market hotel platform. Owns ~30 hotels operated under Marriott, Hyatt and IHG brands across India's top business cities; consolidator of branded mid-market inventory.",
  'Samvardhana Motherson': "Global auto-components supplier. India's largest auto-components company by revenue; supplies wiring harnesses, vision systems (mirrors, lighting), polymer modules and aerospace components to global OEMs across 40+ countries.",
  'Sansera Engineering': "Precision-forged-components specialist. Manufactures connecting rods, rocker arms, crankshafts and aluminium forged parts for two-wheeler, passenger-vehicle, commercial-vehicle and aerospace OEMs in India and globally.",
  'Shyam Metalics & Energy': "Kolkata-headquartered integrated long-product steel producer. Manufactures sponge iron, billets, structurals, wire rods, TMT bars, ferro alloys and aluminium foils; moving up the value chain into stainless steel and specialty products.",
  'Siemens Limited': "Indian subsidiary of Siemens AG (Germany). Industrial automation, drives, smart infrastructure (buildings, low-voltage power) and mobility (rail rolling stock, signalling); the energy assets have been carved out into separately listed Siemens Energy India.",
  'State Bank of India': "India's largest commercial bank (government-owned). Universal-banking franchise across retail, corporate, international and treasury; major subsidiaries in life insurance (SBI Life), asset management (SBI Mutual Fund), credit cards (SBI Cards) and capital markets (SBI Caps).",
  'Sterlite Tech': "Optical-fibre and digital-networks company. Manufactures optical fibre (preform-to-cable integrated), data-centre cabling and network solutions; serves telecom operators, hyperscalers and government broadband programmes.",
  'Sun Pharmaceuticals': "India's largest pharma company. Strong specialty/branded pharma franchise globally (Ilumya in psoriasis, Cequa in dry eye, Winlevi in dermatology); #1 in Indian formulations and a top-three generics player in the US.",
  'Sun TV Network': "South-Indian broadcaster. Operates 30+ regional channels across Tamil, Telugu, Kannada, Malayalam and Bengali, alongside an OTT play (Sun NXT) and an IPL franchise (Sunrisers Hyderabad).",
  'TBO Tek': "Global travel-distribution platform. B2B platform connecting global travel suppliers (airlines, hotels, tour operators, transfers) with 150,000+ travel buyers across 100+ countries.",
  'TCI Express': "Express-logistics company. Surface express transportation for B2B small and large parcels across India; asset-light hub-and-spoke network with a dedicated fleet, partner trucks and centralised sorting hubs.",
  'TTK Prestige': "TTK Group's branded kitchenware company. India's #1 pressure-cooker brand (Prestige) alongside cookware, kitchen appliances (mixer grinders, induction cooktops) and modular kitchens. Strong dealer network and exclusive-brand outlets.",
  'Tata Comm': "Tata Communications — a global telecom and digital-services major. Operates one of the world's largest tier-1 wholesale-IP backbones and undersea-cable networks, enterprise managed-network and unified-communications services, plus growing media-services and IoT verticals.",
  'Tata Consumer Products': "Tata Group's FMCG flagship. Branded tea (Tata Tea, Tetley — world's #2), coffee (Tata Coffee), salt (Tata Salt — market leader), pulses (Tata Sampann) and a growing branded-foods portfolio (8 PM, Soulfull, Ching's Secret); also runs the Starbucks JV in India.",
  'Tata Motors': "Tata Group automobile flagship. Commercial-vehicles market leader in India (heavy/medium trucks, buses, LCVs), passenger-vehicles franchise built on Nexon, Punch, Harrier, Safari and a growing EV portfolio (Nexon EV, Punch EV, Tigor EV), plus the global luxury arm Jaguar Land Rover.",
  'TeamLease Services': "Staffing and HR-services major. India's largest temp-staffing platform serving 6,500+ employers across IT, ITeS, BFSI, retail and manufacturing; also runs degree-apprenticeship, payroll, training and skilling businesses.",
  'The Ramco Cement': "South-Indian cement major (Ramco Group). Strong dealer-led brand position in Tamil Nadu, Andhra Pradesh, Karnataka and Kerala, expanding into Eastern India; product range covers grey cement, blended cement, ready-mix concrete and dry-mortar products.",
  'Titagarh': "Titagarh Rail Systems — railway-wagon, rolling-stock and metro-rail-coach manufacturer. Among India's largest private wagon makers, building metro trainsets (Pune, Surat, Ahmedabad) and Vande Bharat rake supplies; also runs a small shipbuilding business.",
  'Torrent Pharmaceuticals': "Torrent Group's domestic-formulation pharma flagship. Strong franchises in cardiovascular, central-nervous-system and gastrointestinal therapies in India; growing presence in Brazil, the US and Germany.",
  'Varroc Engineering': "Auto-components supplier. Makes lighting (head/tail/fog lamps), electrical-electronics and polymer modules for two-wheelers and four-wheelers; sold the four-wheeler lighting business to Plastic Omnium (2022) to focus on two-wheeler lighting.",
  'Varun Beverages': "PepsiCo's largest franchise bottler outside the United States. Bottles and distributes Pepsi, 7Up, Mountain Dew, Mirinda, Sting, Aquafina and Tropicana across India (most of the country), Sri Lanka, Nepal, Morocco, Zambia, Zimbabwe and DRC.",
  'Vinati Organics': "Specialty-chemicals producer. World's largest manufacturer of ATBS (acrylamido tertiary butyl sulphonic acid — for water treatment, EOR, personal care) and IBB (a paracetamol intermediate); growing portfolio in butyl phenols and antioxidants.",
  'Welspun Living': "Welspun Group's home-textiles major. Among the world's largest manufacturers of terry towels and bed linen, supplying global retailers (Walmart, Target, Macy's) under private labels alongside own brands (Welspun, Spaces) in India.",
  'Whirlpool of India': "Indian subsidiary of Whirlpool Corporation (US). Manufactures refrigerators, washing machines, microwaves and air conditioners under the Whirlpool brand; strong share in single-door refrigerators and semi-automatic washing machines.",
};

let updated = 0, missing = [];
for (const [name, desc] of Object.entries(DESCS)){
  if (!companies[name]){ missing.push(name); continue; }
  companies[name].desc = desc;
  updated++;
}

// Validate every company now has a desc.
const stillBlank = Object.keys(companies).filter(k => !companies[k].desc).sort();

const lines = Object.entries(companies).map(([k, v]) =>
  '  ' + JSON.stringify(k) + ': ' + JSON.stringify(v));
fs.writeFileSync(file, '{\n' + lines.join(',\n') + '\n}\n');

console.log(`Updated descriptions: ${updated}`);
if (missing.length) console.log(`Missing in companies.json (no entry):`, missing);
if (stillBlank.length){
  console.log(`Still without desc (${stillBlank.length}):`);
  stillBlank.forEach(n => console.log(' ', n));
} else {
  console.log('All companies have a description.');
}
